apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
  namespace: 
  labels:
    app.kubernetes.io/name: 
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 
    spec:
      containers:
      - name: 
        image: 
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 
            memory: 
          limits:
            cpu: 
            memory: 
        command:
        - null
        args:
        - null
        ports:
        - name: 
          protocol: TCP
          containerPort: 
        volumeMounts:
        - name: 
          mountPath: 
        startupProbe:
          tcpSocket:
            port: 
          initialDelaySeconds: 
          timeoutSeconds: 
          periodSeconds: 
          successThreshold: 
          failureThreshold: 
        livenessProbe:
          tcpSocket:
            port: 
          initialDelaySeconds: 
          timeoutSeconds: 
          periodSeconds: 
          successThreshold: 
          failureThreshold: 
        readinessProbe:
          tcpSocket:
            port: 
          initialDelaySeconds: 
          timeoutSeconds: 
          periodSeconds: 
          successThreshold: 
          failureThreshold: 
        env:
        - name: 
          value: 
      volumes:
      - name: 
        persistentVolumeClaim:
          claimName: 
