---
- hosts: all
  become: yes

  vars:
    users_add:
    - username: "{{ lookup('env', 'USER') }}"
      shell: /usr/bin/zsh
      append: yes
    packages_install:
      all:
      - subversion
      - tmux
      - neovim
      - git
      archlinux:
      - the_silver_searcher
      - npm
      - python-pynvim
      debian:
      - silversearcher-ag
      - python3-neovim
      redhat:
      - the_silver_searcher
      - python3-neovim
    dotfiles_repo_url: https://github.com/budimanjojo/dotfiles.git
    dotfiles_repo_local_path: ~/.dotfiles
    dotfiles_become: no
    dotfiles_files:
    - .zshrc
    - .zsh
    - .tmux.conf
    - .vimrc
    - .config/nvim
    - .vim/templates
    dotfiles_create_dir:
    - .zsh
    - .config/nvim
    - .vim/templates
    zinit_become: no
    vimplug_vim_cmd: nvim
    vimplug_plugins:
    - name: junegunn/vim-easy-align
    - name: flazz/vim-colorschemes
    - name: chriskempson/base16-vim
    - name: vim-airline/vim-airline
    - name: vim-airline/vim-airline-themes
    - name: scrooloose/nerdtree
    - name: Xuyuanp/nerdtree-git-plugin
    - name: tomtom/tcomment_vim
    - name: tpope/vim-fugitive
    - name: w0rp/ale
    - name: neoclide/coc.nvim
      options:
        branch: release
    - name: honza/vim-snippets
    - name: junegunn/fzf.vim
    - name: Yggdroot/indentLine

  roles:
  - budimanjojo.users
  - budimanjojo.packages
  - budimanjojo.dotfiles
  - budimanjojo.zinit
  - budimanjojo.packages
  - budimanjojo.nodejs
  - budimanjojo.dotfiles
  - budimanjojo.vimplug
  - budimanjojo.packages
  - budimanjojo.dotfiles
