format = """
â•­â”€ \
$username\
$hostname\
$directory\
$git_status\
$git_branch\
$fill\
$status\
$cmd_duration\
$go\
$helm\
$nodejs\
$python\
$vagrant\
$kubernetes\
$time\
$line_break\
â•°â”€\
$character
"""

add_newline = false

[username]
style_user = "yellow"
style_root = "red"
format = "[ï€‡ $user î‚±]($style) "
show_always = true

[hostname]
ssh_only = false
format = "[ï„‰  $hostname î‚±]($style) "
style = "green"

[directory]
truncation_length = 3
format = "[ï¼  $path î‚±]($style)[$read_only]($read_only_style) "
style = "blue"
read_only = " ï€£"
truncation_symbol = "../"
truncate_to_repo = true

[git_branch]
format = "[$symbol$branch î‚±]($style) "
style = "purple"
symbol = "ï„¦ "

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "purple"
conflicted = "â‰­ "
ahead = "ï€› "
behind = "ï€š "
diverged = "â‡• "
up_to_date = "âœ” "
untracked = "ï™ "
stashed = "ï€œ "
modified = "ïª "
staged = "ï• "
renamed = "â©"
deleted = "ğŸ—‘ "

[fill]
symbol = " "

[status]
disabled = false
format = '[î‚³ $symbol]($style) '
symbol = "âœ˜ "
success_symbol = "âœ” "
style = "red"

[cmd_duration]
min_time = "2_000"
format = "î‚³ took [$duration]($style) "
style = "yellow"

[golang]
style = "yellow bold"
format = "[î‚³ $symbol($version)]($style) "

[helm]
style = "yellow bold"
format = "[î‚³ $symbol($version)]($style) "

[nodejs]
style = "yellow bold"
not_capable_style = "red bold"
format = "[î‚³ $symbol($version)]($style) "

[python]
style = "yellow bold"
format = "[î‚³ $symbol($version)]($style) "

[vagrant]
style = "yellow bold"
format = "[î‚³ $symbol($version)]($style) "

[kubernetes]
disabled = false
format = '[î‚³ $symbol$context( \($namespace\))]($style) '
style = "blue bold"
symbol = "â›µ"
[kubernetes.context_aliases]
"kubernetes-admin@cluster.local" = "kubernetes-admin@cluster"

[time]
disabled = false
style = "purple bold"
format = "[î‚³ $time]($style) "
time_format = "ï³  %a, %d %b | ï€—  %I:%M %p "

[character]
success_symbol = "[â®](green)"
error_symbol = "[â®](green)"
vicmd_symbol = "[â®Ÿ](purple)"
